CREATE TABLE `pastes` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `timesent` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `encryption` enum('ENC_3DES','ENC_PLAIN') NOT NULL DEFAULT 'ENC_PLAIN',
  `code` blob NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=137 DEFAULT CHARSET=utf8
